config/routes.rb
Website::Application.routes.draw do

  resources :authorizations

  get "dashboard" => "homepage#dashboard"

  resources :bets do
    resources :wagers, :only =>[:index, :show, :new, :create]
  end
  resource :account, :controller => "users", :only => [:new, :create, :destroy, :edit, :update]
  resource :user_session
  resources :users, :only => [:index, :show]
  
  root :controller => "homepage", :action => "index"
  

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_filter :require_user, :only => [:dashboard]
  
  def index
    redirect_to dashboard_url if current_user.present?
  end

  def dashboard
  end

end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/dashboard.html.erb
<% content_for :title, 'Dashboard' %>

<h2>Bets</h2>
<table>
	<tr>
		<th>Bet</th>
		<th>Wagers</th>
		<th></th>
		<th></th>
	</tr>

	<% current_user.bets.active.each do |bet| %>
		<tr>
			<td><%= link_to bet.title, bet %></td>
			<td><%= bet.wagers.map(&:amount).inject(:+) || 0 %> total credits waged</td>
			<td><%= link_to bet.wagers.count || 0 %> total wagers</td>
			<td><%= content_tag :span, "Expired", :class => "expired" unless bet.active? %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'See All Bets', bets_path %> | <%= link_to 'New Bet', new_bet_path %>


<h2>Active Wagers</h2>
<table>
	<tr>
		<th>Bet</th>
		<th>Wagers</th>
		<th></th>
	</tr>
	<% (current_user.wagers.select{|w| w.active?}).each do |wager| %>
		<tr>
			<td><%= link_to wager.bet.title, wager.bet %></td>
			<td><%= wager.bet.wagers.map(&:amount).inject(:+) %> total credits waged</td>
			<td><%= wager.amount %> waged by you</td>
		</tr>
	<% end %>
</table>

<%= link_to 'Edit', edit_account_path %>

app/views/homepage/index.html.erb
<% content_for :title, 'Welcome' %>
<%= link_to "Login", new_user_session_path %> | <%= link_to "Sign up", new_account_path %>