config/routes.rb
Website::Application.routes.draw do

  resources :authorizations

  get "dashboard" => "homepage#dashboard"

  resources :bets do
    resources :wagers, :only =>[:index, :show, :new, :create]
  end
  resource :account, :controller => "users", :only => [:new, :create, :destroy, :edit, :update]
  resource :user_session
  resources :users, :only => [:index, :show]
  
  root :controller => "homepage", :action => "index"
  

end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :user

  has_many :bet_options, :autosave => true, :dependent => :destroy
  has_many :wagers
  belongs_to :winning_option, :class_name => "BetOption"

  validates_presence_of :title, :expires_at, :user_id
  
  accepts_nested_attributes_for :bet_options, :allow_destroy => true, :reject_if => :all_blank

  scope :active, where('expires_at > ?', DateTime.now)

  def active?
    self.expires_at > DateTime.now
  end
  
  def report_result!(option_id, current_user)
    return false unless user == current_user && winning_option_id.blank? && option_id.present?
    self.winning_option_id = option_id
    self.expires_at = DateTime.now if active?
    self.save!
    
    #Calculate all totals
    totals = {}
    self.wagers.each do |wager|
      totals[wager.bet_option.id] ||= 0
      totals[wager.bet_option.id] += wager.amount
    end
    
    #Calculate winning total
    winning_total = totals[winning_option_id] || 0
    
    #Refund wager totals down to winning total in input ratio
    self.wagers.each do |wager|
      if wager.win?
        wager.refund = wager.amount
      else
        if totals[winning_option_id] < totals[wager.bet_option.id]
          wager.refund = ((wager.amount.to_f / totals[wager.bet_option.id].to_f) * (totals[wager.bet_option.id].to_f - totals[winning_option_id].to_f)).floor
        else
          wager.refund = 0
        end
      end
      wager.save!
      wager.user.points += wager.refund
      wager.user.save!
    end
    
    #Drop totals down to accomodate refunds (we do this in a second step so we can use floor in the previous each statement)
    #also calc win/loss totals
    total_win = 0
    total_loss = 0
    totals.each do |key, value|
      totals[key] = totals[winning_option_id] if value > totals[winning_option_id]
      total_win += totals[key] if key == winning_option_id
      total_loss += totals[key] unless key == winning_option_id
    end

    #calc win per credit
    self.win_per_credit = total_loss.to_f / total_win.to_f rescue 0
    result = self.save!

    #update wager win amounts and assign points
    self.wagers.each do |wager|
      if wager.win?
        wager.win_amount = (win_per_credit * wager.amount).floor
        wager.user.points += wager.win_amount
        wager.user.save!
      else
        wager.win_amount = -wager.amount
      end
      wager.save!
    end

  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  before_filter :require_user 
  def index
    @bets = Bet.active
  end

  def show
    @bet = Bet.find(params[:id])
  end

  def new
    @bet = Bet.new
    5.times { @bet.bet_options.build }
    @bet.expires_at = DateTime.tomorrow
  end

  def edit
    @bet = Bet.find(params[:id])
    unless @bet.user == current_user
      redirect_to @bet, notice: 'You cannot edit that bet, because you didnt create it'
    end
  end

  def create
    @bet = Bet.new(params[:bet])
    @bet.user = current_user
    
    if @bet.save
      redirect_to @bet, notice: 'Bet was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @bet = Bet.find(params[:id])

    if @bet.report_result!(params[:bet][:winning_option], current_user)
      redirect_to @bet, notice: 'Bet result successfully reported.'
    else
      render action: "edit"
    end
  end

  def destroy
    @bet = Bet.find(params[:id])
    @bet.destroy
    redirect_to action: "index", notice: 'Bet was successfully deleted.'
  end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= form_for @bet do |f| %>
  <% if @bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bet.errors.count, "error") %> prohibited this bet from being saved:</h2>

      <ul>
      <% @bet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl class="actions">
	  <dt><%= f.label :title %></dt>
	  <dd><%= f.text_field :title %></dd>
	  <dt><%= f.label :description %></dt>
	  <dd><%= f.text_area :description, :rows => 5, :cols => 50 %></dd>
	  <dt><%= f.label :expires_at %></dt>
	  <dd><%= f.text_field :expires_at %></dd>
		<% i = 0 %>
		<%= f.fields_for :bet_options do |bet_option_fields| %>
		  <dt><%= bet_option_fields.label :label, "Option #{i=i+1}" %></dt>
		  <dd><%= bet_option_fields.text_field :label %></dd>
    <% end %>
		<dt></dt>
		<dd><%= f.submit "Save" %></dd>
  </dl>
<% end %>

app/views/bets/edit.html.erb
<% content_for :title, 'Report Bet Result' %>

<%= form_for @bet do |f| %>
	<% @bet.bet_options.each do |bet_option| %>
		<%= f.radio_button 'winning_option', bet_option.id %><%= f.label "winning_option_#{bet_option.id}", "#{bet_option.label} (#{bet_option.wagers.map(&:amount).inject(:+) || 0} waged credits)" %><br/>
	<% end %>
	<%= f.submit 'Report Result' %>
	
<% end %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>

app/views/bets/index.html.erb
<% content_for :title, 'Listing bets' %>


<table>
  <tr>
		<th>Id</th>
		<th>User</th>
		<th>Title</th>
		<th>Description</th>
		<th>Options</th>
		<th>Expires at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bets.each do |bet| %>
  <tr>
		<td><%= bet.id %></td>
		<td><%= bet.user.login %></td>
		<td><%= bet.title %></td>
		<td><%= bet.description %></td>
		<td><%= bet.bet_options.map(&:label).join(', ') %></td>
		<td><%= bet.expires_at %></td>
    <td><%= link_to 'Show', bet %></td>
    <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
    <td><%= link_to 'Destroy', bet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bet', new_bet_path %>

app/views/bets/new.html.erb
<% content_for :title, 'New bet' %>

<%= render 'form' %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<% content_for :title, @bet.title %>

<dl>
	<dt>Id</dt>
	<dd><%= @bet.id %></dd>
	<dt>User</dt>
	<dd><%= @bet.user.login %><dd>
	<dt>Title</dt>
	<dd><%= @bet.title %><dd>
	<dt>Description</dt>
	<dd><%= @bet.description %><dd>
	<dt>Expires_at</dt>
	<dd><%= @bet.expires_at %><dd>
	<% if @bet.active? %>
		<dt>Place Bet</dt>
		<dd><%= render :partial => "wagers/form", :locals => {:wager => @bet.wagers.build} %><dd>
	<% else %>
		<dt>Options</dt>
		<dd>
			<% @bet.bet_options.each do |o| %>
				<span <%="style='font-weight:bold;'" if o.win? %>><%= o.label %></span> <%="(#{o.wagers.map(&:amount).inject(:+) || 0} waged credits)" %> <br/>
			<% end %>
		</dd>
	<% end %>
	<% %>
</dl>

<% if @bet.user == current_user %>
	<%= link_to 'Report Result', edit_bet_path(@bet) %> |
<% end %>
<%= link_to 'Back', bets_path %> |
<%= link_to 'See Wagers', bet_wagers_path(@bet) %>