config/routes.rb
Website::Application.routes.draw do

  resources :authorizations

  get "dashboard" => "homepage#dashboard"

  resources :bets do
    resources :wagers, :only =>[:index, :show, :new, :create]
  end
  resource :account, :controller => "users", :only => [:new, :create, :destroy, :edit, :update]
  resource :user_session
  resources :users, :only => [:index, :show]
  
  root :controller => "homepage", :action => "index"
  

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  
  has_many :bets
  has_many :wagers
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:index, :show, :edit, :update]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
      redirect_back_or_default dashboard_url
    else
      render :action => :new
    end
  end
  
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/views/users/_form.html.erb
<dl>
<dt><%= form.label :login %></dt>
<dd><%= form.text_field :login %></dd>

<dt><%= form.label :password, form.object.new_record? ? nil : "Change password" %></dt>
<dd><%= form.password_field :password %></dd>

<dt><%= form.label :password_confirmation %></dt>
<dd><%= form.password_field :password_confirmation %></dd>
</dl>

app/views/users/edit.html.erb
<% content_for :title, 'Edit My Account' %>

<%= form_for @user, :url => account_path do |f| %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update" %>
<% end %>

<br /><%= link_to "My Profile", account_path %>

app/views/users/index.html.erb
<table>
	<% @users.each do |user| %>
	<tr>
		<td><%= link_to user.login, user %></td>
	</tr>
	<% end %>
</table>

app/views/users/new.html.erb
<% content_for :title, 'Register' %>

<%= form_for @user, :url => account_path do |f| %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<% content_for :title, "#{@user.login}'s Profile" %>

<%=@user.points%> Points

<h2>Bets</h2>
<table>
	<% @user.bets.active.each do |bet| %>
		<tr>
			<td><%= link_to bet.title, bet %></td>
			<td><%= bet.wagers.map(&:amount).inject(:+) %> total credits waged</td>
			<td><%= link_to bet.wagers.count %> total wagers</td>
			<td><%= content_tag :span, "Expired", :class => "expired" unless bet.active? %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'See All Bets', bets_path %> | <%= link_to 'New Bet', new_bet_path %>


<h2>Active Wagers</h2>
<table>
	<% (@user.wagers.select{|w| w.active?}).each do |wager| %>
		<tr>
			<td><%= link_to wager.bet.title, wager.bet %></td>
			<td><%= wager.bet.wagers.map(&:amount).inject(:+) %> total credits waged</td>
			<td><%= wager.amount %> waged by this user</td>
		</tr>
	<% end %>
</table>

<h2>Past Wagers</h2>
<table>
	<% (@user.wagers.reverse.select{|w| !w.active?}).each do |wager| %>
		<tr <%="style='font-weight:bold;'" if wager.win? %>>
			<td><%= link_to wager.bet.title, wager.bet %></td>
			<td><%= wager.amount %> waged by this user</td>
			<td><%= wager.win? ? "WIN (+#{wager.win_amount} credits)" : "LOSS" %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'Back', users_path %>